
import React from 'react';
import { 
  Diamond, 
  MessageCircle, 
  User, 
  Search, 
  CheckCircle2, 
  XCircle, 
  Heart, 
  Award,
  Send,
  MoreVertical,
  ChevronLeft,
  MapPin,
  Briefcase,
  GraduationCap,
  Banknote,
  Plus,
  LayoutDashboard,
  Users,
  ShieldCheck,
  BarChart3,
  LogOut,
  Settings,
  Sparkles,
  Smartphone,
  CreditCard,
  Footprints,
  Eye,
  AlertTriangle
} from 'lucide-react';

export const Icons = {
  Diamond: (props: any) => React.createElement(Diamond, props),
  Message: (props: any) => React.createElement(MessageCircle, props),
  User: (props: any) => React.createElement(User, props),
  Search: (props: any) => React.createElement(Search, props),
  Verify: (props: any) => React.createElement(CheckCircle2, props),
  Reject: (props: any) => React.createElement(XCircle, props),
  Heart: (props: any) => React.createElement(Heart, props),
  Award: (props: any) => React.createElement(Award, props),
  Send: (props: any) => React.createElement(Send, props),
  More: (props: any) => React.createElement(MoreVertical, props),
  Back: (props: any) => React.createElement(ChevronLeft, props),
  Location: (props: any) => React.createElement(MapPin, props),
  Job: (props: any) => React.createElement(Briefcase, props),
  School: (props: any) => React.createElement(GraduationCap, props),
  Money: (props: any) => React.createElement(Banknote, props),
  Plus: (props: any) => React.createElement(Plus, props),
  Dashboard: (props: any) => React.createElement(LayoutDashboard, props),
  Users: (props: any) => React.createElement(Users, props),
  Admin: (props: any) => React.createElement(ShieldCheck, props),
  Chart: (props: any) => React.createElement(BarChart3, props),
  Logout: (props: any) => React.createElement(LogOut, props),
  Settings: (props: any) => React.createElement(Settings, props),
  Sparkles: (props: any) => React.createElement(Sparkles, props),
  Phone: (props: any) => React.createElement(Smartphone, props),
  Card: (props: any) => React.createElement(CreditCard, props),
  Footprints: (props: any) => React.createElement(Footprints, props),
  Eye: (props: any) => React.createElement(Eye, props),
  Alert: (props: any) => React.createElement(AlertTriangle, props),
};
